In [1]:
import numpy as np

In [15]:
features = np.array([1,2])

In [16]:
features.shape

(2,)

In [4]:
w = np.array([3,4])
w = features.reshape(1,2)
w.shape

(1, 2)

In [6]:
from sklearn.linear_model import Perceptron

In [20]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])
model = Perceptron()
model.fit(X,y)
model.score(X,y)
model.predict([[0,1]])

array([0])

In [26]:
a= [[1,2],[3,4]]
type(a)

a= np.array([[1,2],[3,4]])
a.shape
a
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [28]:
np.array??

In [27]:
demand = np.array([[8,1],[5,5],[2,7]])
prices = np.array([[10,5],[8,10]])
np.dot(demand,prices)

array([[88, 50],
       [90, 75],
       [76, 80]])